//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_EF_SQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int id_produto { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string imagem { get; set; }
        public System.DateTime datacadastro { get; set; }
        public int id_categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
